export default {
    tasksList: state => state.tasksList,
    taskQueue: state => state.taskQueue,
    currentTask: state => state.currentTask,
    isStarted: state => state.started,
    isStopped: state => state.stopped,
    isPaused: state => state.paused,
    hasTasks: state => state.taskQueue.length > 0,
    currentTaskIndex: state => state.currentTaskIndex,
    willRefresh: state => state.willRefresh,
    isWorking: state => state.isWorking,
    minutes: state => Math.floor(state.counter / 60),
    seconds: state => state.counter % 60,
    standartWorkingTime: state => state.standartWorkingTime,
    restingTime: state => state.restingTime,
    theAudio: state => state.theAudio,
    workSound: state => state.workSound,
    restSound: state => state.restSound,
}
